import { query, getClient } from '../config/db';
import { Totalisator } from '../core/totalisator';
import { emitMarketStatusUpdate } from './socketService';
import { SchedulerService } from './schedulerService';

// ============================================================
// Market Group Management
// ============================================================

export const createMarketGroup = async (
    title: string,
    description?: string,
    category: string = 'General',
    image_url?: string
) => {
    const result = await query(
        `INSERT INTO market_groups (title, description, category, image_url)
         VALUES ($1, $2, $3, $4) RETURNING *`,
        [title, description || null, category, image_url || null]
    );
    return result.rows[0];
};

export const listMarketGroups = async () => {
    // Fetch all groups with their child markets
    const groupsRes = await query(
        `SELECT * FROM market_groups ORDER BY created_at DESC`
    );
    const groups = groupsRes.rows;

    if (groups.length === 0) return [];

    // Fetch all markets that belong to any group
    const marketsRes = await query(
        `SELECT * FROM markets WHERE group_id IS NOT NULL ORDER BY created_at ASC`
    );

    // Attach markets to their groups
    const marketsByGroup: Record<string, any[]> = {};
    for (const m of marketsRes.rows) {
        if (!marketsByGroup[m.group_id]) marketsByGroup[m.group_id] = [];
        marketsByGroup[m.group_id].push(m);
    }

    return groups.map((g: any) => ({
        ...g,
        markets: marketsByGroup[g.id] || []
    }));
};

export const deleteMarketGroup = async (groupId: string, deleteMarkets: boolean = false) => {
    const client = await getClient();
    try {
        await client.query('BEGIN');

        if (deleteMarkets) {
            // Delete wagers for all markets in the group first
            await client.query(
                `DELETE FROM wagers WHERE market_id IN (SELECT id FROM markets WHERE group_id = $1)`,
                [groupId]
            );
            // Delete the child markets
            await client.query(
                `DELETE FROM markets WHERE group_id = $1`,
                [groupId]
            );
        } else {
            // Unlink markets from the group (set group_id to NULL)
            await client.query(
                `UPDATE markets SET group_id = NULL WHERE group_id = $1`,
                [groupId]
            );
        }

        // Delete the group itself
        const result = await client.query(
            `DELETE FROM market_groups WHERE id = $1 RETURNING *`,
            [groupId]
        );

        await client.query('COMMIT');

        if (result.rows.length === 0) throw new Error('Market group not found');
        return result.rows[0];
    } catch (e: any) {
        await client.query('ROLLBACK');
        throw e;
    } finally {
        client.release();
    }
};

// ============================================================
// Market Creation
// ============================================================

export const createMarketService = async (
    title: string,
    durationOrTimestamp: number | string,
    initYes: number,
    initNo: number,
    sourceOfTruth: string = 'Generated by AI',
    confidenceScore: number = 0.85,
    resolutionTimestamp?: number | string,
    category: string = 'Other',
    term: string = 'Ultra Short',
    // New parameters for multi-option & groups
    marketType: string = 'BINARY',
    options: string[] = [],
    groupId?: string,
    initLiquidity?: number
) => {
    let closureTime: number;
    let resolutionTime: number;

    if (typeof durationOrTimestamp === 'string' && !isNaN(Number(durationOrTimestamp)) && durationOrTimestamp.length > 10) {
        closureTime = Number(durationOrTimestamp);
    } else if (typeof durationOrTimestamp === 'string') {
        closureTime = new Date(durationOrTimestamp).getTime();
    } else if (typeof durationOrTimestamp === 'number' && durationOrTimestamp > 1000000000000) {
        closureTime = durationOrTimestamp;
    } else {
        closureTime = Date.now() + (Number(durationOrTimestamp) * 1000);
    }

    if (resolutionTimestamp) {
        resolutionTime = typeof resolutionTimestamp === 'string'
            ? new Date(resolutionTimestamp).getTime()
            : resolutionTimestamp;
    } else {
        resolutionTime = closureTime + (30 * 60 * 1000);
    }

    // Build pools and initial liquidity based on market type
    let poolYes = 0;
    let poolNo = 0;
    let pools: Record<string, number> = {};
    let totalPool = 0;

    // Sanitize option keys: strip special characters, keep only safe chars for DB constraints
    const sanitizeKey = (s: string): string =>
        s.toLowerCase().trim()
            .replace(/[^a-z0-9 _-]/g, '')  // Remove arrows, commas, special chars
            .replace(/\s+/g, ' ')           // Collapse whitespace
            .trim()
            .substring(0, 100)              // Enforce VARCHAR(100) limit
        || 'option';                        // Fallback if empty after sanitize

    // Sanitize options for MULTI markets before any processing
    if (marketType === 'MULTI' && options.length >= 2) {
        options = options.map((opt: string) => {
            // Capitalize first letter of sanitized key for display
            const clean = sanitizeKey(opt);
            return clean.charAt(0).toUpperCase() + clean.slice(1);
        });
    }

    if (marketType === 'MULTI' && options.length >= 2) {
        // Distribute liquidity evenly across all options
        const totalLiq = initLiquidity || (initYes + initNo) || 0;
        const perOption = totalLiq > 0 ? Math.floor(totalLiq / options.length) : 0;

        for (const opt of options) {
            const key = sanitizeKey(opt);
            pools[key] = perOption;
        }
        totalPool = perOption * options.length;
    } else {
        // Standard binary market
        poolYes = initYes || 0;
        poolNo = initNo || 0;
        totalPool = poolYes + poolNo;
    }

    const result = await query(
        `INSERT INTO markets (title, status, closure_timestamp, resolution_timestamp, pool_yes, pool_no, pools, source_of_truth, confidence_score, category, term, market_type, options, group_id) 
         VALUES ($1, 'OPEN', $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING *`,
        [title, closureTime, resolutionTime, poolYes, poolNo, JSON.stringify(pools), sourceOfTruth, confidenceScore, category, term, marketType, JSON.stringify(options), groupId || null]
    );

    const newMarket = result.rows[0];

    // Audit Trail: Create wagers for initial liquidity
    const hasLiquidity = marketType === 'MULTI'
        ? totalPool > 0
        : (initYes > 0 || initNo > 0);

    if (hasLiquidity) {
        try {
            // 1. Get or create System Merchant (Safely handle concurrency)
            let systemMerchantRes = await query(
                `INSERT INTO merchants (api_key_hash, raw_api_key, config) 
                 VALUES ('system_liquidity_hash', 'system_liquidity_key', $1)
                 ON CONFLICT (api_key_hash) DO UPDATE SET config = excluded.config
                 RETURNING id`,
                [JSON.stringify({ name: 'System Liquidity', default_rake: 0 })]
            );
            const systemMerchantId = systemMerchantRes.rows[0].id;

            if (marketType === 'MULTI') {
                // Create a wager for each option's initial liquidity
                for (const opt of options) {
                    const key = sanitizeKey(opt);
                    const amount = pools[key];
                    if (amount > 0) {
                        await query(
                            "INSERT INTO wagers (merchant_id, market_id, selection, stake, status) VALUES ($1, $2, $3, $4, $5)",
                            [systemMerchantId, newMarket.id, key, amount, 'ACCEPTED']
                        );
                    }
                }
            } else {
                // Standard binary audit wagers
                if (initYes > 0) {
                    await query(
                        "INSERT INTO wagers (merchant_id, market_id, selection, stake, status) VALUES ($1, $2, $3, $4, $5)",
                        [systemMerchantId, newMarket.id, 'yes', initYes, 'ACCEPTED']
                    );
                }
                if (initNo > 0) {
                    await query(
                        "INSERT INTO wagers (merchant_id, market_id, selection, stake, status) VALUES ($1, $2, $3, $4, $5)",
                        [systemMerchantId, newMarket.id, 'no', initNo, 'ACCEPTED']
                    );
                }
            }
        } catch (auditError) {
            console.error('[MarketService] Failed to create audit wagers:', auditError);
            // We don't fail the whole market creation, but we log it
        }
    }

    // Automatically register event-driven jobs
    SchedulerService.scheduleMarketJobs(newMarket);

    return newMarket;
};

// ============================================================
// Market Settlement
// ============================================================

export const settleMarket = async (marketId: string, outcome: string) => {
    const client = await getClient();

    try {
        await client.query('BEGIN');

        // 1. Lock and get market
        const marketRes = await client.query('SELECT * FROM markets WHERE id = $1 FOR UPDATE', [marketId]);
        if (marketRes.rows.length === 0) throw new Error('Market not found');
        const market = marketRes.rows[0];

        if (market.status === 'SETTLED') {
            await client.query('ROLLBACK');
            client.release();
            return { success: true, message: 'Market already settled' } as any;
        }

        // Build pool data based on market type
        let poolData: Record<string, number> = {};
        const marketType = market.market_type || 'BINARY';

        if (marketType === 'MULTI') {
            // Use the pools JSONB for multi-option markets
            poolData = market.pools || {};

            // Validate outcome is one of the defined options
            const validOptions = (market.options || []).map((o: string) => o.toLowerCase().trim());
            if (validOptions.length > 0 && !validOptions.includes(outcome.toLowerCase())) {
                throw new Error(`Invalid outcome "${outcome}". Valid options: ${validOptions.join(', ')}`);
            }
        } else {
            // Binary market: use pool_yes/pool_no or pools JSONB
            if (market.pools && Object.keys(market.pools).length > 0) {
                poolData = market.pools;
            } else {
                poolData = {
                    yes: Number(market.pool_yes || 0),
                    no: Number(market.pool_no || 0)
                };
            }
        }

        const normalizedOutcome = outcome.toLowerCase().trim();

        // 2. Fetch all wagers for this market
        const wagersRes = await client.query('SELECT * FROM wagers WHERE market_id = $1', [marketId]);
        const wagers = wagersRes.rows;

        // 3. Calculate and update payouts
        let totalPayoutsCalculated = 0;

        for (const wager of wagers) {
            let payout = 0;
            if (wager.selection === normalizedOutcome) {
                // Fetch merchant rake
                const merchantRes = await client.query('SELECT config FROM merchants WHERE id = $1', [wager.merchant_id]);
                const rake = merchantRes.rows[0]?.config?.default_rake;

                payout = Totalisator.calculatePotentialPayout(Number(wager.stake), poolData, normalizedOutcome, rake);
                totalPayoutsCalculated += payout;
            }

            await client.query(
                'UPDATE wagers SET payout = $1, status = $2, settled_at = NOW() WHERE id = $3',
                [payout, 'SETTLED', wager.id]
            );
        }

        // --- Post-Calculation Sanity Check ---
        const totalPoolCollected = Object.values(poolData).reduce((sum, val) => sum + val, 0);
        if (totalPayoutsCalculated > totalPoolCollected + 0.01) { // 0.01 buffer for tiny float diffs
            throw new Error(`Solvency Alert: Calculated payouts ($${totalPayoutsCalculated}) exceed total pool ($${totalPoolCollected}). Settlement aborted.`);
        }

        // 4. Update market status
        await client.query(
            'UPDATE markets SET status = $1, outcome = $2 WHERE id = $3',
            ['SETTLED', normalizedOutcome, marketId]
        );

        await client.query('COMMIT');

        const { LoggerService } = await import('./loggerService');
        await LoggerService.info(`[Settlement] ✅ Market ${marketId} settled as ${normalizedOutcome.toUpperCase()}`, {
            marketId,
            outcome: normalizedOutcome,
            wagerCount: wagers.length,
            poolData
        });

        emitMarketStatusUpdate(marketId, 'SETTLED');

        // 5. Trigger Webhook Notifications for involved merchants (outside transaction)
        try {
            const { WebhookService } = await import('./webhookService');
            const finalWagersRes = await query('SELECT * FROM wagers WHERE market_id = $1', [marketId]);
            const finalWagers = finalWagersRes.rows;

            const uniqueMerchants = [...new Set(finalWagers.map(w => w.merchant_id))];
            for (const merchantId of uniqueMerchants) {
                const merchantWagers = finalWagers.filter(w => w.merchant_id === merchantId);
                await WebhookService.notifySettlement(merchantId, marketId, 'SETTLED', normalizedOutcome, merchantWagers);
            }
        } catch (webhookError: any) {
            console.error(`[Settlement] Webhook delivery failed for market ${marketId}:`, webhookError.message);
            // Don't throw — settlement was already committed successfully
        }

        return { success: true, wagerCount: wagers.length };
    } catch (e: any) {
        await client.query('ROLLBACK');
        const { LoggerService } = await import('./loggerService');
        await LoggerService.error(`[Settlement] ❌ Settlement failed for Market ${marketId}: ${e.message}`, {
            marketId,
            error: e.message,
            stack: e.stack
        });
        throw e;
    } finally {
        client.release();
    }
};

// ============================================================
// Market Voiding
// ============================================================

export const voidMarket = async (marketId: string) => {
    const client = await getClient();

    try {
        await client.query('BEGIN');

        // 1. Lock and get market
        const marketRes = await client.query('SELECT * FROM markets WHERE id = $1 FOR UPDATE', [marketId]);
        if (marketRes.rows.length === 0) throw new Error('Market not found');
        const market = marketRes.rows[0];

        if (market.status === 'SETTLED' || market.status === 'VOID') {
            throw new Error(`Market already ${market.status.toLowerCase()}`);
        }

        // 2. Refund all wagers in bulk
        const refundRes = await client.query(
            'UPDATE wagers SET payout = stake, status = $1, settled_at = NOW() WHERE market_id = $2',
            ['VOIDED', marketId]
        );
        const wagerCount = refundRes.rowCount || 0;

        // 4. Update market status
        await client.query(
            'UPDATE markets SET status = $1 WHERE id = $2',
            ['VOIDED', marketId]
        );

        await client.query('COMMIT');

        const { LoggerService } = await import('./loggerService');
        await LoggerService.warn(`[Void] ⚠️ Market ${marketId} voided and ${wagerCount} wagers refunded`, {
            marketId,
            wagerCount
        });

        emitMarketStatusUpdate(marketId, 'VOIDED');

        return { success: true, wagerCount };
    } catch (e: any) {
        await client.query('ROLLBACK');
        const { LoggerService } = await import('./loggerService');
        await LoggerService.error(`[Void] ❌ Void failed for Market ${marketId}: ${e.message}`, {
            marketId,
            error: e.message
        });
        throw e;
    } finally {
        client.release();
    }
};

// ============================================================
// Market Closure
// ============================================================

export const closeMarket = async (marketId: string) => {
    const client = await getClient();
    try {
        await client.query('BEGIN');

        // 1. Lock and get status
        const marketRes = await client.query('SELECT status FROM markets WHERE id = $1 FOR UPDATE', [marketId]);
        if (marketRes.rows.length === 0) throw new Error('Market not found');

        const currentStatus = marketRes.rows[0].status;

        // Idempotency check
        if (currentStatus === 'CLOSED' || currentStatus === 'SETTLED' || currentStatus === 'VOIDED' || currentStatus === 'RESOLVING') {
            await client.query('ROLLBACK');
            return true; // Consider it done
        }

        // 2. Update status
        await client.query("UPDATE markets SET status = 'CLOSED' WHERE id = $1", [marketId]);

        await client.query('COMMIT');

        const { LoggerService } = await import('./loggerService');
        await LoggerService.info(`[Close] 🔒 Market ${marketId} closed manually/via watchdog.`, { marketId });

        emitMarketStatusUpdate(marketId, 'CLOSED');

        return true;
    } catch (e: any) {
        await client.query('ROLLBACK');
        const { LoggerService } = await import('./loggerService');
        await LoggerService.error(`[Close] ❌ Close failed for Market ${marketId}: ${e.message}`, { marketId, error: e.message });
        throw e;
    } finally {
        client.release();
    }
};
